# .github/workflows/run-pathfinder-nodes.yml

name: Run Pathfinder Nodes

on:
  push:
    branches:
      - p2p-e2e-tests

jobs:
  run-pathfinder-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: p2p-e2e-tests

      - name: Set up Environment
        run: |
          mkdir -p feeder_data
          mkdir -p peer_data
          echo '{"private_key":"CAESQArAo83bMrNgftGfokSJ0XcP26bgn6WL3vXUhqUR8BbVVPsL0F/dGWu+VZPcnP3DhH24s5EaHVOinqv2BEkbfdc=","peer_id":"12D3KooWFY6SaqJkRxJDepwvBi4Rw36iMUGZrejW69qkjYQQ2ydQ"}' > pathfinder_identity.json

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait for Nodes to Initialize
        run: sleep 600

      - name: Display Feeder Node Logs
        run: docker logs feeder-node

      - name: Display Peer Node Logs
        run: docker logs peer-node